// <auto-generated />

using System;
using System.Linq;
using System.Collections.Generic;
using Microsoft.Xrm.Sdk;
using Microsoft.Xrm.Sdk.Query;
using Microsoft.Crm.Sdk.Messages;
using Microsoft.Xrm.Sdk.Messages;
using Microsoft.Xrm.Sdk.Metadata;
using Microsoft.Xrm.Sdk.Client;
using System.Threading.Tasks;
using System.ComponentModel;
using System.Runtime.Serialization;

namespace NHSBT.IRDP.Plugins.ProxyClasses
{
    [EntityLogicalNameAttribute("nhs_rarebloodsource")]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XrmToolkit", "4.0")]
    [DataContract(Name = "Entity", Namespace = "http://schemas.microsoft.com/xrm/2011/Contracts")]
    public partial class RareBloodSource : BaseProxyClass
    {
        public new const string LogicalName = "nhs_rarebloodsource";
        public const int ObjectTypeCode = 10067;
        public const string PrimaryIdAttribute = "nhs_rarebloodsourceid";
        public const string PrimaryNameAttribute = "nhs_panelcode";
        
        static RareBloodSource()
        {
            BaseProxyClass.RegisterProxyType(typeof(RareBloodSource), "nhs_rarebloodsource");
            _textOptions = new Dictionary<string, eTextOptions>();
            _numberOptions = new Dictionary<string, eNumberOptions>();
            _errorStrings = new Dictionary<string, string>();
            TextError = "The value for attribute '{0}' cannot be longer than {3} characters. The length of the value is {2} characters.";
            NumberError = "The value for attribute '{0}' must be between {2} and {3}. The value is {1}";
        }
        public RareBloodSource() : base(new Entity("nhs_rarebloodsource")) { }
        public RareBloodSource(Entity original) : base(original) { }
        public static string GetLogicalName() { return BaseProxyClass.GetLogicalName<RareBloodSource>(); }
        /// <summary>
        /// Action to perform when the string value is greater than the allowed length.
        /// <para>This is the default for any string attribute in this Entity</para>
        /// </summary>
        public static eTextOptions TextOptions { get; set; }
        private static Dictionary<string, eTextOptions> _textOptions;
        /// <summary>
        /// Use this to set an action and error string when a value is greater than the allowed length
        /// </summary>
        /// <param name="logicalName">Name of Attribute</param>
        /// <param name="options">Action to perform when the value is greater than the allowed length</param>
        /// <param name="errorString">Optional: Error to throw if the eTextOptions == ThrowError
        /// <para>If nothing is specified then the 'TextError' string is used.</para>
        /// <para>You may use the following parameters:</para>
        /// <para>{0} = Attribute Logical Name</para>
        /// <para>{1} = Value</para>
        /// <para>{2} = Length</para>
        /// <para>{3} = Max Length</para>
        /// </param>
        public static void SetTextOptions(string logicalName, eTextOptions options, string errorString = null)
        {
            if (_textOptions.ContainsKey(logicalName)) { _textOptions[logicalName] = options; }
            else { _textOptions.Add(logicalName, options); }
            if (!string.IsNullOrEmpty(errorString))
            {
                if (_errorStrings.ContainsKey(logicalName)) { _errorStrings[logicalName] = errorString; }
                else { _errorStrings.Add(logicalName, errorString); }
            }
            else if (_errorStrings.ContainsKey(logicalName)) { _errorStrings.Remove(logicalName); }
        }
        protected override eTextOptions GetTextOptions(string logicalName)
        {
            if (_textOptions.ContainsKey(logicalName)) { return _textOptions[logicalName]; }
            return TextOptions;
        }
        /// <summary>
        /// Action to perform when the number value is greater or less than the allowed value.
        /// <para>This is the default for any int, decimal, double, or money attribute in this Entity</para>
        /// </summary>
        public static eNumberOptions NumberOptions { get; set; }
        private static Dictionary<string, eNumberOptions> _numberOptions;
        /// <summary>
        /// Use this to set an action and error string when a value is greater or less than the allowed value
        /// </summary>
        /// <param name="logicalName">Name of Attribute</param>
        /// <param name="options">Action to perform when the value is greater or less than the allowed value</param>
        /// <param name="errorString">Optional: Error to throw if the eNumberOptions == ThrowError
        /// <para>If nothing is specified then the 'NumberError' string is used.</para>
        /// <para>You may use the following parameters:</para>
        /// <para>{0} = Attribute Logical Name</para>
        /// <para>{1} = Value</para>
        /// <para>{2} = Min Value</para>
        /// <para>{3} = Max Value</para>
        /// </param>
        public static void SetNumberOptions(string logicalName, eNumberOptions options, string errorString = null)
        {
            if (_numberOptions.ContainsKey(logicalName)) { _numberOptions[logicalName] = options; }
            else { _numberOptions.Add(logicalName, options); }
            if (!string.IsNullOrEmpty(errorString))
            {
                if (_errorStrings.ContainsKey(logicalName)) { _errorStrings[logicalName] = errorString; }
                else { _errorStrings.Add(logicalName, errorString); }
            }
            else if (_errorStrings.ContainsKey(logicalName)) { _errorStrings.Remove(logicalName); }
        }
        protected override eNumberOptions GetNumberOptions(string logicalName)
        {
            if (_numberOptions.ContainsKey(logicalName)) { return _numberOptions[logicalName]; }
            return NumberOptions;
        }
        private static Dictionary<string, string> _errorStrings;
        protected override string GetErrorString(string attributeName, BaseProxyClass.eErrorType defaultErrorType)
        {
            if (_errorStrings.ContainsKey(attributeName))
            {
                return _errorStrings[attributeName];
            }
            return defaultErrorType == BaseProxyClass.eErrorType.Text ? TextError : NumberError;
        }
        /// <summary>
        /// <para>Default error string is: The value for attribute '{0}' cannot be longer than {3} characters. The length of the value is {2} characters.</para>
        /// <para>You may use the following parameters</para>
        /// <para>{0} = Attribute Name</para>
        /// <para>{1} = Value</para>
        /// <para>{2} = Length</para>
        /// <para>{3} = Max Length</para>
        /// </summary>
        public static string TextError { get; set; }
        /// <summary>
        /// <para>Default error string is: The value for attribute '{0}' must be between {2} and {3}. The value is {1}.</para>
        /// <para>You may use the following parameters</para>
        /// <para>{0} = Attribute Name</para>
        /// <para>{1} = Value</para>
        /// <para>{2} = Min Value</para>
        /// <para>{3} = Max Value</para>
        /// </summary>
        public static string NumberError { get; set; }

        ///<summary>
///<para>Logical Name: nhs_parentaccountyominame</para>
///<para>Max Length: 160 characters</para>
///</summary>
[AttributeLogicalNameAttribute("nhs_parentaccountyominame")]
public string Nhs_ParentAccountYomiName
{
	get { return this.GetPropertyValue<string>("nhs_parentaccountyominame"); }
}
///<summary>
///<para>Logical Name: modifiedbyyominame</para>
///<para>Max Length: 100 characters</para>
///</summary>
[AttributeLogicalNameAttribute("modifiedbyyominame")]
public string ModifiedByYomiName
{
	get { return this.GetPropertyValue<string>("modifiedbyyominame"); }
}
///<summary>
///<para>Logical Name: owneridtype</para>
///</summary>
[AttributeLogicalNameAttribute("owneridtype")]
public string OwnerIdType
{
	get { return this.GetPropertyValue<string>("owneridtype"); }
	set { this.SetPropertyValue<string>("owneridtype", value, "OwnerIdType"); }
}
///<summary>
///<para>Logical Name: modifiedbyname</para>
///<para>Max Length: 100 characters</para>
///</summary>
[AttributeLogicalNameAttribute("modifiedbyname")]
public string ModifiedByName
{
	get { return this.GetPropertyValue<string>("modifiedbyname"); }
}
///<summary>
///<para>Logical Name: owneridname</para>
///<para>Max Length: 100 characters</para>
///</summary>
[AttributeLogicalNameAttribute("owneridname")]
public string OwnerIdName
{
	get { return this.GetPropertyValue<string>("owneridname"); }
}
///<summary>
///<para>Logical Name: nhs_parentaccountname</para>
///<para>Max Length: 160 characters</para>
///</summary>
[AttributeLogicalNameAttribute("nhs_parentaccountname")]
public string Nhs_ParentAccountName
{
	get { return this.GetPropertyValue<string>("nhs_parentaccountname"); }
}
///<summary>
///<para>Logical Name: createdonbehalfbyyominame</para>
///<para>Max Length: 100 characters</para>
///</summary>
[AttributeLogicalNameAttribute("createdonbehalfbyyominame")]
public string CreatedOnBehalfByYomiName
{
	get { return this.GetPropertyValue<string>("createdonbehalfbyyominame"); }
}
///<summary>
///<para>Logical Name: createdonbehalfbyname</para>
///<para>Max Length: 100 characters</para>
///</summary>
[AttributeLogicalNameAttribute("createdonbehalfbyname")]
public string CreatedOnBehalfByName
{
	get { return this.GetPropertyValue<string>("createdonbehalfbyname"); }
}
///<summary>
///<para>Logical Name: owneridyominame</para>
///<para>Max Length: 100 characters</para>
///</summary>
[AttributeLogicalNameAttribute("owneridyominame")]
public string OwnerIdYomiName
{
	get { return this.GetPropertyValue<string>("owneridyominame"); }
}
///<summary>
///<para>Logical Name: createdbyname</para>
///<para>Max Length: 100 characters</para>
///</summary>
[AttributeLogicalNameAttribute("createdbyname")]
public string CreatedByName
{
	get { return this.GetPropertyValue<string>("createdbyname"); }
}
///<summary>
///<para>Logical Name: modifiedonbehalfbyname</para>
///<para>Max Length: 100 characters</para>
///</summary>
[AttributeLogicalNameAttribute("modifiedonbehalfbyname")]
public string ModifiedOnBehalfByName
{
	get { return this.GetPropertyValue<string>("modifiedonbehalfbyname"); }
}
///<summary>
///<para>Logical Name: createdbyyominame</para>
///<para>Max Length: 100 characters</para>
///</summary>
[AttributeLogicalNameAttribute("createdbyyominame")]
public string CreatedByYomiName
{
	get { return this.GetPropertyValue<string>("createdbyyominame"); }
}
///<summary>
///<para>Logical Name: modifiedonbehalfbyyominame</para>
///<para>Max Length: 100 characters</para>
///</summary>
[AttributeLogicalNameAttribute("modifiedonbehalfbyyominame")]
public string ModifiedOnBehalfByYomiName
{
	get { return this.GetPropertyValue<string>("modifiedonbehalfbyyominame"); }
}
/// <summary>
///Logical Name: nhs_abotype
/// </summary>
[AttributeLogicalNameAttribute("nhs_abotype")]
public eABOSub_types? ABOType
{
	get
	{
		if (ABOType_OptionSetValue != null) { return (eABOSub_types)ABOType_OptionSetValue.Value; }
		return null;
	}
	set
	{
		if (value != null) { this.ABOType_OptionSetValue = new OptionSetValue((int)value); }
		else this.ABOType_OptionSetValue = null;
	}
}
///<summary>
///<para>Logical Name: nhs_abotype</para>
///</summary>
[AttributeLogicalNameAttribute("nhs_abotype")]
public OptionSetValue ABOType_OptionSetValue
{
	get { return this.GetPropertyValue<OptionSetValue>("nhs_abotype"); }
	set { this.SetPropertyValue<OptionSetValue>("nhs_abotype", value, "ABOType_OptionSetValue"); }
}
/// <summary>
/// Retrieves the current value's text in the user's language.
/// </summary>
/// <param name="Service">CRM Organization Service</param>
/// <returns></returns>
public string ABOType_Text(IOrganizationService Service)
{
	return this.ABOType_OptionSetValue.GetOptionSetText(Service, this, "nhs_abotype");
}
/// <summary>
/// Retrieves the current value's text in the user's language.
/// </summary>
/// <param name="AttributeMetadata">The attribute metadata previously retrieved using the 'GetAttributeMetadata' extension method on the IOrganizationService object.</param>
/// <returns></returns>
public string ABOType_Text(EnumAttributeMetadata AttributeMetadata)
{
	return AttributeMetadata.GetOptionSetText(this.ABOType_OptionSetValue.Value);
}
///<summary>
///<para>Logical Name: nhs_alternatekey</para>
///<para>Max Length: 100 characters</para>
///</summary>
[AttributeLogicalNameAttribute("nhs_alternatekey")]
public string AlternateKey
{
	get { return this.GetPropertyValue<string>("nhs_alternatekey"); }
	set { this.SetPropertyValue("nhs_alternatekey", value, 100, "AlternateKey"); }
}
///<summary>
///<para>Logical Name: nhs_antibodies</para>
///<para>Max Length: 50 characters</para>
///</summary>
[AttributeLogicalNameAttribute("nhs_antibodies")]
public string Antibodies
{
	get { return this.GetPropertyValue<string>("nhs_antibodies"); }
	set { this.SetPropertyValue("nhs_antibodies", value, 50, "Antibodies"); }
}
/// <summary>
///Logical Name: nhs_associateantigenoncreate_smallc
/// </summary>
[AttributeLogicalNameAttribute("nhs_associateantigenoncreate_smallc")]
public eAntigenResult_SourceContext? AssociateAntigenOnCreate_C
{
	get
	{
		if (AssociateAntigenOnCreate_C_OptionSetValue != null) { return (eAntigenResult_SourceContext)AssociateAntigenOnCreate_C_OptionSetValue.Value; }
		return null;
	}
	set
	{
		if (value != null) { this.AssociateAntigenOnCreate_C_OptionSetValue = new OptionSetValue((int)value); }
		else this.AssociateAntigenOnCreate_C_OptionSetValue = null;
	}
}
///<summary>
///<para>Logical Name: nhs_associateantigenoncreate_smallc</para>
///</summary>
[AttributeLogicalNameAttribute("nhs_associateantigenoncreate_smallc")]
public OptionSetValue AssociateAntigenOnCreate_C_OptionSetValue
{
	get { return this.GetPropertyValue<OptionSetValue>("nhs_associateantigenoncreate_smallc"); }
	set { this.SetPropertyValue<OptionSetValue>("nhs_associateantigenoncreate_smallc", value, "AssociateAntigenOnCreate_C_OptionSetValue"); }
}
/// <summary>
/// Retrieves the current value's text in the user's language.
/// </summary>
/// <param name="Service">CRM Organization Service</param>
/// <returns></returns>
public string AssociateAntigenOnCreate_C_Text(IOrganizationService Service)
{
	return this.AssociateAntigenOnCreate_C_OptionSetValue.GetOptionSetText(Service, this, "nhs_associateantigenoncreate_smallc");
}
/// <summary>
/// Retrieves the current value's text in the user's language.
/// </summary>
/// <param name="AttributeMetadata">The attribute metadata previously retrieved using the 'GetAttributeMetadata' extension method on the IOrganizationService object.</param>
/// <returns></returns>
public string AssociateAntigenOnCreate_C_Text(EnumAttributeMetadata AttributeMetadata)
{
	return AttributeMetadata.GetOptionSetText(this.AssociateAntigenOnCreate_C_OptionSetValue.Value);
}
/// <summary>
///Logical Name: nhs_associateantigenoncreate_bigc
/// </summary>
[AttributeLogicalNameAttribute("nhs_associateantigenoncreate_bigc")]
public eAntigenResult_SourceContext? AssociateAntigenOnCreate_C2
{
	get
	{
		if (AssociateAntigenOnCreate_C2_OptionSetValue != null) { return (eAntigenResult_SourceContext)AssociateAntigenOnCreate_C2_OptionSetValue.Value; }
		return null;
	}
	set
	{
		if (value != null) { this.AssociateAntigenOnCreate_C2_OptionSetValue = new OptionSetValue((int)value); }
		else this.AssociateAntigenOnCreate_C2_OptionSetValue = null;
	}
}
///<summary>
///<para>Logical Name: nhs_associateantigenoncreate_bigc</para>
///</summary>
[AttributeLogicalNameAttribute("nhs_associateantigenoncreate_bigc")]
public OptionSetValue AssociateAntigenOnCreate_C2_OptionSetValue
{
	get { return this.GetPropertyValue<OptionSetValue>("nhs_associateantigenoncreate_bigc"); }
	set { this.SetPropertyValue<OptionSetValue>("nhs_associateantigenoncreate_bigc", value, "AssociateAntigenOnCreate_C2_OptionSetValue"); }
}
/// <summary>
/// Retrieves the current value's text in the user's language.
/// </summary>
/// <param name="Service">CRM Organization Service</param>
/// <returns></returns>
public string AssociateAntigenOnCreate_C2_Text(IOrganizationService Service)
{
	return this.AssociateAntigenOnCreate_C2_OptionSetValue.GetOptionSetText(Service, this, "nhs_associateantigenoncreate_bigc");
}
/// <summary>
/// Retrieves the current value's text in the user's language.
/// </summary>
/// <param name="AttributeMetadata">The attribute metadata previously retrieved using the 'GetAttributeMetadata' extension method on the IOrganizationService object.</param>
/// <returns></returns>
public string AssociateAntigenOnCreate_C2_Text(EnumAttributeMetadata AttributeMetadata)
{
	return AttributeMetadata.GetOptionSetText(this.AssociateAntigenOnCreate_C2_OptionSetValue.Value);
}
/// <summary>
///Logical Name: nhs_associateantigenoncreate_cw
/// </summary>
[AttributeLogicalNameAttribute("nhs_associateantigenoncreate_cw")]
public eAntigenResult_SourceContext? AssociateAntigenOnCreate_Cw
{
	get
	{
		if (AssociateAntigenOnCreate_Cw_OptionSetValue != null) { return (eAntigenResult_SourceContext)AssociateAntigenOnCreate_Cw_OptionSetValue.Value; }
		return null;
	}
	set
	{
		if (value != null) { this.AssociateAntigenOnCreate_Cw_OptionSetValue = new OptionSetValue((int)value); }
		else this.AssociateAntigenOnCreate_Cw_OptionSetValue = null;
	}
}
///<summary>
///<para>Logical Name: nhs_associateantigenoncreate_cw</para>
///</summary>
[AttributeLogicalNameAttribute("nhs_associateantigenoncreate_cw")]
public OptionSetValue AssociateAntigenOnCreate_Cw_OptionSetValue
{
	get { return this.GetPropertyValue<OptionSetValue>("nhs_associateantigenoncreate_cw"); }
	set { this.SetPropertyValue<OptionSetValue>("nhs_associateantigenoncreate_cw", value, "AssociateAntigenOnCreate_Cw_OptionSetValue"); }
}
/// <summary>
/// Retrieves the current value's text in the user's language.
/// </summary>
/// <param name="Service">CRM Organization Service</param>
/// <returns></returns>
public string AssociateAntigenOnCreate_Cw_Text(IOrganizationService Service)
{
	return this.AssociateAntigenOnCreate_Cw_OptionSetValue.GetOptionSetText(Service, this, "nhs_associateantigenoncreate_cw");
}
/// <summary>
/// Retrieves the current value's text in the user's language.
/// </summary>
/// <param name="AttributeMetadata">The attribute metadata previously retrieved using the 'GetAttributeMetadata' extension method on the IOrganizationService object.</param>
/// <returns></returns>
public string AssociateAntigenOnCreate_Cw_Text(EnumAttributeMetadata AttributeMetadata)
{
	return AttributeMetadata.GetOptionSetText(this.AssociateAntigenOnCreate_Cw_OptionSetValue.Value);
}
/// <summary>
///Logical Name: nhs_associateantigenoncreate_d
/// </summary>
[AttributeLogicalNameAttribute("nhs_associateantigenoncreate_d")]
public eAntigenResult_SourceContext? AssociateAntigenOnCreate_D
{
	get
	{
		if (AssociateAntigenOnCreate_D_OptionSetValue != null) { return (eAntigenResult_SourceContext)AssociateAntigenOnCreate_D_OptionSetValue.Value; }
		return null;
	}
	set
	{
		if (value != null) { this.AssociateAntigenOnCreate_D_OptionSetValue = new OptionSetValue((int)value); }
		else this.AssociateAntigenOnCreate_D_OptionSetValue = null;
	}
}
///<summary>
///<para>Logical Name: nhs_associateantigenoncreate_d</para>
///</summary>
[AttributeLogicalNameAttribute("nhs_associateantigenoncreate_d")]
public OptionSetValue AssociateAntigenOnCreate_D_OptionSetValue
{
	get { return this.GetPropertyValue<OptionSetValue>("nhs_associateantigenoncreate_d"); }
	set { this.SetPropertyValue<OptionSetValue>("nhs_associateantigenoncreate_d", value, "AssociateAntigenOnCreate_D_OptionSetValue"); }
}
/// <summary>
/// Retrieves the current value's text in the user's language.
/// </summary>
/// <param name="Service">CRM Organization Service</param>
/// <returns></returns>
public string AssociateAntigenOnCreate_D_Text(IOrganizationService Service)
{
	return this.AssociateAntigenOnCreate_D_OptionSetValue.GetOptionSetText(Service, this, "nhs_associateantigenoncreate_d");
}
/// <summary>
/// Retrieves the current value's text in the user's language.
/// </summary>
/// <param name="AttributeMetadata">The attribute metadata previously retrieved using the 'GetAttributeMetadata' extension method on the IOrganizationService object.</param>
/// <returns></returns>
public string AssociateAntigenOnCreate_D_Text(EnumAttributeMetadata AttributeMetadata)
{
	return AttributeMetadata.GetOptionSetText(this.AssociateAntigenOnCreate_D_OptionSetValue.Value);
}
/// <summary>
///Logical Name: nhs_associateantigenoncreate_smalle
/// </summary>
[AttributeLogicalNameAttribute("nhs_associateantigenoncreate_smalle")]
public eAntigenResult_SourceContext? AssociateAntigenOnCreate_E
{
	get
	{
		if (AssociateAntigenOnCreate_E_OptionSetValue != null) { return (eAntigenResult_SourceContext)AssociateAntigenOnCreate_E_OptionSetValue.Value; }
		return null;
	}
	set
	{
		if (value != null) { this.AssociateAntigenOnCreate_E_OptionSetValue = new OptionSetValue((int)value); }
		else this.AssociateAntigenOnCreate_E_OptionSetValue = null;
	}
}
///<summary>
///<para>Logical Name: nhs_associateantigenoncreate_smalle</para>
///</summary>
[AttributeLogicalNameAttribute("nhs_associateantigenoncreate_smalle")]
public OptionSetValue AssociateAntigenOnCreate_E_OptionSetValue
{
	get { return this.GetPropertyValue<OptionSetValue>("nhs_associateantigenoncreate_smalle"); }
	set { this.SetPropertyValue<OptionSetValue>("nhs_associateantigenoncreate_smalle", value, "AssociateAntigenOnCreate_E_OptionSetValue"); }
}
/// <summary>
/// Retrieves the current value's text in the user's language.
/// </summary>
/// <param name="Service">CRM Organization Service</param>
/// <returns></returns>
public string AssociateAntigenOnCreate_E_Text(IOrganizationService Service)
{
	return this.AssociateAntigenOnCreate_E_OptionSetValue.GetOptionSetText(Service, this, "nhs_associateantigenoncreate_smalle");
}
/// <summary>
/// Retrieves the current value's text in the user's language.
/// </summary>
/// <param name="AttributeMetadata">The attribute metadata previously retrieved using the 'GetAttributeMetadata' extension method on the IOrganizationService object.</param>
/// <returns></returns>
public string AssociateAntigenOnCreate_E_Text(EnumAttributeMetadata AttributeMetadata)
{
	return AttributeMetadata.GetOptionSetText(this.AssociateAntigenOnCreate_E_OptionSetValue.Value);
}
/// <summary>
///Logical Name: nhs_associateantigenoncreate_bige
/// </summary>
[AttributeLogicalNameAttribute("nhs_associateantigenoncreate_bige")]
public eAntigenResult_SourceContext? AssociateAntigenOnCreate_E2
{
	get
	{
		if (AssociateAntigenOnCreate_E2_OptionSetValue != null) { return (eAntigenResult_SourceContext)AssociateAntigenOnCreate_E2_OptionSetValue.Value; }
		return null;
	}
	set
	{
		if (value != null) { this.AssociateAntigenOnCreate_E2_OptionSetValue = new OptionSetValue((int)value); }
		else this.AssociateAntigenOnCreate_E2_OptionSetValue = null;
	}
}
///<summary>
///<para>Logical Name: nhs_associateantigenoncreate_bige</para>
///</summary>
[AttributeLogicalNameAttribute("nhs_associateantigenoncreate_bige")]
public OptionSetValue AssociateAntigenOnCreate_E2_OptionSetValue
{
	get { return this.GetPropertyValue<OptionSetValue>("nhs_associateantigenoncreate_bige"); }
	set { this.SetPropertyValue<OptionSetValue>("nhs_associateantigenoncreate_bige", value, "AssociateAntigenOnCreate_E2_OptionSetValue"); }
}
/// <summary>
/// Retrieves the current value's text in the user's language.
/// </summary>
/// <param name="Service">CRM Organization Service</param>
/// <returns></returns>
public string AssociateAntigenOnCreate_E2_Text(IOrganizationService Service)
{
	return this.AssociateAntigenOnCreate_E2_OptionSetValue.GetOptionSetText(Service, this, "nhs_associateantigenoncreate_bige");
}
/// <summary>
/// Retrieves the current value's text in the user's language.
/// </summary>
/// <param name="AttributeMetadata">The attribute metadata previously retrieved using the 'GetAttributeMetadata' extension method on the IOrganizationService object.</param>
/// <returns></returns>
public string AssociateAntigenOnCreate_E2_Text(EnumAttributeMetadata AttributeMetadata)
{
	return AttributeMetadata.GetOptionSetText(this.AssociateAntigenOnCreate_E2_OptionSetValue.Value);
}
/// <summary>
///Logical Name: nhs_associateantigenoncreate_fya
/// </summary>
[AttributeLogicalNameAttribute("nhs_associateantigenoncreate_fya")]
public eAntigenResult_SourceContext? AssociateAntigenOnCreate_Fya
{
	get
	{
		if (AssociateAntigenOnCreate_Fya_OptionSetValue != null) { return (eAntigenResult_SourceContext)AssociateAntigenOnCreate_Fya_OptionSetValue.Value; }
		return null;
	}
	set
	{
		if (value != null) { this.AssociateAntigenOnCreate_Fya_OptionSetValue = new OptionSetValue((int)value); }
		else this.AssociateAntigenOnCreate_Fya_OptionSetValue = null;
	}
}
///<summary>
///<para>Logical Name: nhs_associateantigenoncreate_fya</para>
///</summary>
[AttributeLogicalNameAttribute("nhs_associateantigenoncreate_fya")]
public OptionSetValue AssociateAntigenOnCreate_Fya_OptionSetValue
{
	get { return this.GetPropertyValue<OptionSetValue>("nhs_associateantigenoncreate_fya"); }
	set { this.SetPropertyValue<OptionSetValue>("nhs_associateantigenoncreate_fya", value, "AssociateAntigenOnCreate_Fya_OptionSetValue"); }
}
/// <summary>
/// Retrieves the current value's text in the user's language.
/// </summary>
/// <param name="Service">CRM Organization Service</param>
/// <returns></returns>
public string AssociateAntigenOnCreate_Fya_Text(IOrganizationService Service)
{
	return this.AssociateAntigenOnCreate_Fya_OptionSetValue.GetOptionSetText(Service, this, "nhs_associateantigenoncreate_fya");
}
/// <summary>
/// Retrieves the current value's text in the user's language.
/// </summary>
/// <param name="AttributeMetadata">The attribute metadata previously retrieved using the 'GetAttributeMetadata' extension method on the IOrganizationService object.</param>
/// <returns></returns>
public string AssociateAntigenOnCreate_Fya_Text(EnumAttributeMetadata AttributeMetadata)
{
	return AttributeMetadata.GetOptionSetText(this.AssociateAntigenOnCreate_Fya_OptionSetValue.Value);
}
/// <summary>
///Logical Name: nhs_associateantigenoncreate_fyb
/// </summary>
[AttributeLogicalNameAttribute("nhs_associateantigenoncreate_fyb")]
public eAntigenResult_SourceContext? AssociateAntigenOnCreate_Fyb
{
	get
	{
		if (AssociateAntigenOnCreate_Fyb_OptionSetValue != null) { return (eAntigenResult_SourceContext)AssociateAntigenOnCreate_Fyb_OptionSetValue.Value; }
		return null;
	}
	set
	{
		if (value != null) { this.AssociateAntigenOnCreate_Fyb_OptionSetValue = new OptionSetValue((int)value); }
		else this.AssociateAntigenOnCreate_Fyb_OptionSetValue = null;
	}
}
///<summary>
///<para>Logical Name: nhs_associateantigenoncreate_fyb</para>
///</summary>
[AttributeLogicalNameAttribute("nhs_associateantigenoncreate_fyb")]
public OptionSetValue AssociateAntigenOnCreate_Fyb_OptionSetValue
{
	get { return this.GetPropertyValue<OptionSetValue>("nhs_associateantigenoncreate_fyb"); }
	set { this.SetPropertyValue<OptionSetValue>("nhs_associateantigenoncreate_fyb", value, "AssociateAntigenOnCreate_Fyb_OptionSetValue"); }
}
/// <summary>
/// Retrieves the current value's text in the user's language.
/// </summary>
/// <param name="Service">CRM Organization Service</param>
/// <returns></returns>
public string AssociateAntigenOnCreate_Fyb_Text(IOrganizationService Service)
{
	return this.AssociateAntigenOnCreate_Fyb_OptionSetValue.GetOptionSetText(Service, this, "nhs_associateantigenoncreate_fyb");
}
/// <summary>
/// Retrieves the current value's text in the user's language.
/// </summary>
/// <param name="AttributeMetadata">The attribute metadata previously retrieved using the 'GetAttributeMetadata' extension method on the IOrganizationService object.</param>
/// <returns></returns>
public string AssociateAntigenOnCreate_Fyb_Text(EnumAttributeMetadata AttributeMetadata)
{
	return AttributeMetadata.GetOptionSetText(this.AssociateAntigenOnCreate_Fyb_OptionSetValue.Value);
}
/// <summary>
///Logical Name: nhs_associateantigenoncreate_jka
/// </summary>
[AttributeLogicalNameAttribute("nhs_associateantigenoncreate_jka")]
public eAntigenResult_SourceContext? AssociateAntigenOnCreate_Jka
{
	get
	{
		if (AssociateAntigenOnCreate_Jka_OptionSetValue != null) { return (eAntigenResult_SourceContext)AssociateAntigenOnCreate_Jka_OptionSetValue.Value; }
		return null;
	}
	set
	{
		if (value != null) { this.AssociateAntigenOnCreate_Jka_OptionSetValue = new OptionSetValue((int)value); }
		else this.AssociateAntigenOnCreate_Jka_OptionSetValue = null;
	}
}
///<summary>
///<para>Logical Name: nhs_associateantigenoncreate_jka</para>
///</summary>
[AttributeLogicalNameAttribute("nhs_associateantigenoncreate_jka")]
public OptionSetValue AssociateAntigenOnCreate_Jka_OptionSetValue
{
	get { return this.GetPropertyValue<OptionSetValue>("nhs_associateantigenoncreate_jka"); }
	set { this.SetPropertyValue<OptionSetValue>("nhs_associateantigenoncreate_jka", value, "AssociateAntigenOnCreate_Jka_OptionSetValue"); }
}
/// <summary>
/// Retrieves the current value's text in the user's language.
/// </summary>
/// <param name="Service">CRM Organization Service</param>
/// <returns></returns>
public string AssociateAntigenOnCreate_Jka_Text(IOrganizationService Service)
{
	return this.AssociateAntigenOnCreate_Jka_OptionSetValue.GetOptionSetText(Service, this, "nhs_associateantigenoncreate_jka");
}
/// <summary>
/// Retrieves the current value's text in the user's language.
/// </summary>
/// <param name="AttributeMetadata">The attribute metadata previously retrieved using the 'GetAttributeMetadata' extension method on the IOrganizationService object.</param>
/// <returns></returns>
public string AssociateAntigenOnCreate_Jka_Text(EnumAttributeMetadata AttributeMetadata)
{
	return AttributeMetadata.GetOptionSetText(this.AssociateAntigenOnCreate_Jka_OptionSetValue.Value);
}
/// <summary>
///Logical Name: nhs_associateantigenoncreate_jkb
/// </summary>
[AttributeLogicalNameAttribute("nhs_associateantigenoncreate_jkb")]
public eAntigenResult_SourceContext? AssociateAntigenOnCreate_Jkb
{
	get
	{
		if (AssociateAntigenOnCreate_Jkb_OptionSetValue != null) { return (eAntigenResult_SourceContext)AssociateAntigenOnCreate_Jkb_OptionSetValue.Value; }
		return null;
	}
	set
	{
		if (value != null) { this.AssociateAntigenOnCreate_Jkb_OptionSetValue = new OptionSetValue((int)value); }
		else this.AssociateAntigenOnCreate_Jkb_OptionSetValue = null;
	}
}
///<summary>
///<para>Logical Name: nhs_associateantigenoncreate_jkb</para>
///</summary>
[AttributeLogicalNameAttribute("nhs_associateantigenoncreate_jkb")]
public OptionSetValue AssociateAntigenOnCreate_Jkb_OptionSetValue
{
	get { return this.GetPropertyValue<OptionSetValue>("nhs_associateantigenoncreate_jkb"); }
	set { this.SetPropertyValue<OptionSetValue>("nhs_associateantigenoncreate_jkb", value, "AssociateAntigenOnCreate_Jkb_OptionSetValue"); }
}
/// <summary>
/// Retrieves the current value's text in the user's language.
/// </summary>
/// <param name="Service">CRM Organization Service</param>
/// <returns></returns>
public string AssociateAntigenOnCreate_Jkb_Text(IOrganizationService Service)
{
	return this.AssociateAntigenOnCreate_Jkb_OptionSetValue.GetOptionSetText(Service, this, "nhs_associateantigenoncreate_jkb");
}
/// <summary>
/// Retrieves the current value's text in the user's language.
/// </summary>
/// <param name="AttributeMetadata">The attribute metadata previously retrieved using the 'GetAttributeMetadata' extension method on the IOrganizationService object.</param>
/// <returns></returns>
public string AssociateAntigenOnCreate_Jkb_Text(EnumAttributeMetadata AttributeMetadata)
{
	return AttributeMetadata.GetOptionSetText(this.AssociateAntigenOnCreate_Jkb_OptionSetValue.Value);
}
/// <summary>
///Logical Name: nhs_associateantigenoncreate_smallk
/// </summary>
[AttributeLogicalNameAttribute("nhs_associateantigenoncreate_smallk")]
public eAntigenResult_SourceContext? AssociateAntigenOnCreate_K
{
	get
	{
		if (AssociateAntigenOnCreate_K_OptionSetValue != null) { return (eAntigenResult_SourceContext)AssociateAntigenOnCreate_K_OptionSetValue.Value; }
		return null;
	}
	set
	{
		if (value != null) { this.AssociateAntigenOnCreate_K_OptionSetValue = new OptionSetValue((int)value); }
		else this.AssociateAntigenOnCreate_K_OptionSetValue = null;
	}
}
///<summary>
///<para>Logical Name: nhs_associateantigenoncreate_smallk</para>
///</summary>
[AttributeLogicalNameAttribute("nhs_associateantigenoncreate_smallk")]
public OptionSetValue AssociateAntigenOnCreate_K_OptionSetValue
{
	get { return this.GetPropertyValue<OptionSetValue>("nhs_associateantigenoncreate_smallk"); }
	set { this.SetPropertyValue<OptionSetValue>("nhs_associateantigenoncreate_smallk", value, "AssociateAntigenOnCreate_K_OptionSetValue"); }
}
/// <summary>
/// Retrieves the current value's text in the user's language.
/// </summary>
/// <param name="Service">CRM Organization Service</param>
/// <returns></returns>
public string AssociateAntigenOnCreate_K_Text(IOrganizationService Service)
{
	return this.AssociateAntigenOnCreate_K_OptionSetValue.GetOptionSetText(Service, this, "nhs_associateantigenoncreate_smallk");
}
/// <summary>
/// Retrieves the current value's text in the user's language.
/// </summary>
/// <param name="AttributeMetadata">The attribute metadata previously retrieved using the 'GetAttributeMetadata' extension method on the IOrganizationService object.</param>
/// <returns></returns>
public string AssociateAntigenOnCreate_K_Text(EnumAttributeMetadata AttributeMetadata)
{
	return AttributeMetadata.GetOptionSetText(this.AssociateAntigenOnCreate_K_OptionSetValue.Value);
}
/// <summary>
///Logical Name: nhs_associateantigenoncreate_bigk
/// </summary>
[AttributeLogicalNameAttribute("nhs_associateantigenoncreate_bigk")]
public eAntigenResult_SourceContext? AssociateAntigenOnCreate_K2
{
	get
	{
		if (AssociateAntigenOnCreate_K2_OptionSetValue != null) { return (eAntigenResult_SourceContext)AssociateAntigenOnCreate_K2_OptionSetValue.Value; }
		return null;
	}
	set
	{
		if (value != null) { this.AssociateAntigenOnCreate_K2_OptionSetValue = new OptionSetValue((int)value); }
		else this.AssociateAntigenOnCreate_K2_OptionSetValue = null;
	}
}
///<summary>
///<para>Logical Name: nhs_associateantigenoncreate_bigk</para>
///</summary>
[AttributeLogicalNameAttribute("nhs_associateantigenoncreate_bigk")]
public OptionSetValue AssociateAntigenOnCreate_K2_OptionSetValue
{
	get { return this.GetPropertyValue<OptionSetValue>("nhs_associateantigenoncreate_bigk"); }
	set { this.SetPropertyValue<OptionSetValue>("nhs_associateantigenoncreate_bigk", value, "AssociateAntigenOnCreate_K2_OptionSetValue"); }
}
/// <summary>
/// Retrieves the current value's text in the user's language.
/// </summary>
/// <param name="Service">CRM Organization Service</param>
/// <returns></returns>
public string AssociateAntigenOnCreate_K2_Text(IOrganizationService Service)
{
	return this.AssociateAntigenOnCreate_K2_OptionSetValue.GetOptionSetText(Service, this, "nhs_associateantigenoncreate_bigk");
}
/// <summary>
/// Retrieves the current value's text in the user's language.
/// </summary>
/// <param name="AttributeMetadata">The attribute metadata previously retrieved using the 'GetAttributeMetadata' extension method on the IOrganizationService object.</param>
/// <returns></returns>
public string AssociateAntigenOnCreate_K2_Text(EnumAttributeMetadata AttributeMetadata)
{
	return AttributeMetadata.GetOptionSetText(this.AssociateAntigenOnCreate_K2_OptionSetValue.Value);
}
/// <summary>
///Logical Name: nhs_associateantigenoncreate_lea
/// </summary>
[AttributeLogicalNameAttribute("nhs_associateantigenoncreate_lea")]
public eAntigenResult_SourceContext? AssociateAntigenOnCreate_Lea
{
	get
	{
		if (AssociateAntigenOnCreate_Lea_OptionSetValue != null) { return (eAntigenResult_SourceContext)AssociateAntigenOnCreate_Lea_OptionSetValue.Value; }
		return null;
	}
	set
	{
		if (value != null) { this.AssociateAntigenOnCreate_Lea_OptionSetValue = new OptionSetValue((int)value); }
		else this.AssociateAntigenOnCreate_Lea_OptionSetValue = null;
	}
}
///<summary>
///<para>Logical Name: nhs_associateantigenoncreate_lea</para>
///</summary>
[AttributeLogicalNameAttribute("nhs_associateantigenoncreate_lea")]
public OptionSetValue AssociateAntigenOnCreate_Lea_OptionSetValue
{
	get { return this.GetPropertyValue<OptionSetValue>("nhs_associateantigenoncreate_lea"); }
	set { this.SetPropertyValue<OptionSetValue>("nhs_associateantigenoncreate_lea", value, "AssociateAntigenOnCreate_Lea_OptionSetValue"); }
}
/// <summary>
/// Retrieves the current value's text in the user's language.
/// </summary>
/// <param name="Service">CRM Organization Service</param>
/// <returns></returns>
public string AssociateAntigenOnCreate_Lea_Text(IOrganizationService Service)
{
	return this.AssociateAntigenOnCreate_Lea_OptionSetValue.GetOptionSetText(Service, this, "nhs_associateantigenoncreate_lea");
}
/// <summary>
/// Retrieves the current value's text in the user's language.
/// </summary>
/// <param name="AttributeMetadata">The attribute metadata previously retrieved using the 'GetAttributeMetadata' extension method on the IOrganizationService object.</param>
/// <returns></returns>
public string AssociateAntigenOnCreate_Lea_Text(EnumAttributeMetadata AttributeMetadata)
{
	return AttributeMetadata.GetOptionSetText(this.AssociateAntigenOnCreate_Lea_OptionSetValue.Value);
}
/// <summary>
///Logical Name: nhs_associateantigenoncreate_leb
/// </summary>
[AttributeLogicalNameAttribute("nhs_associateantigenoncreate_leb")]
public eAntigenResult_SourceContext? AssociateAntigenOnCreate_Leb
{
	get
	{
		if (AssociateAntigenOnCreate_Leb_OptionSetValue != null) { return (eAntigenResult_SourceContext)AssociateAntigenOnCreate_Leb_OptionSetValue.Value; }
		return null;
	}
	set
	{
		if (value != null) { this.AssociateAntigenOnCreate_Leb_OptionSetValue = new OptionSetValue((int)value); }
		else this.AssociateAntigenOnCreate_Leb_OptionSetValue = null;
	}
}
///<summary>
///<para>Logical Name: nhs_associateantigenoncreate_leb</para>
///</summary>
[AttributeLogicalNameAttribute("nhs_associateantigenoncreate_leb")]
public OptionSetValue AssociateAntigenOnCreate_Leb_OptionSetValue
{
	get { return this.GetPropertyValue<OptionSetValue>("nhs_associateantigenoncreate_leb"); }
	set { this.SetPropertyValue<OptionSetValue>("nhs_associateantigenoncreate_leb", value, "AssociateAntigenOnCreate_Leb_OptionSetValue"); }
}
/// <summary>
/// Retrieves the current value's text in the user's language.
/// </summary>
/// <param name="Service">CRM Organization Service</param>
/// <returns></returns>
public string AssociateAntigenOnCreate_Leb_Text(IOrganizationService Service)
{
	return this.AssociateAntigenOnCreate_Leb_OptionSetValue.GetOptionSetText(Service, this, "nhs_associateantigenoncreate_leb");
}
/// <summary>
/// Retrieves the current value's text in the user's language.
/// </summary>
/// <param name="AttributeMetadata">The attribute metadata previously retrieved using the 'GetAttributeMetadata' extension method on the IOrganizationService object.</param>
/// <returns></returns>
public string AssociateAntigenOnCreate_Leb_Text(EnumAttributeMetadata AttributeMetadata)
{
	return AttributeMetadata.GetOptionSetText(this.AssociateAntigenOnCreate_Leb_OptionSetValue.Value);
}
/// <summary>
///Logical Name: nhs_associateantigenoncreate_m
/// </summary>
[AttributeLogicalNameAttribute("nhs_associateantigenoncreate_m")]
public eAntigenResult_SourceContext? AssociateAntigenOnCreate_M
{
	get
	{
		if (AssociateAntigenOnCreate_M_OptionSetValue != null) { return (eAntigenResult_SourceContext)AssociateAntigenOnCreate_M_OptionSetValue.Value; }
		return null;
	}
	set
	{
		if (value != null) { this.AssociateAntigenOnCreate_M_OptionSetValue = new OptionSetValue((int)value); }
		else this.AssociateAntigenOnCreate_M_OptionSetValue = null;
	}
}
///<summary>
///<para>Logical Name: nhs_associateantigenoncreate_m</para>
///</summary>
[AttributeLogicalNameAttribute("nhs_associateantigenoncreate_m")]
public OptionSetValue AssociateAntigenOnCreate_M_OptionSetValue
{
	get { return this.GetPropertyValue<OptionSetValue>("nhs_associateantigenoncreate_m"); }
	set { this.SetPropertyValue<OptionSetValue>("nhs_associateantigenoncreate_m", value, "AssociateAntigenOnCreate_M_OptionSetValue"); }
}
/// <summary>
/// Retrieves the current value's text in the user's language.
/// </summary>
/// <param name="Service">CRM Organization Service</param>
/// <returns></returns>
public string AssociateAntigenOnCreate_M_Text(IOrganizationService Service)
{
	return this.AssociateAntigenOnCreate_M_OptionSetValue.GetOptionSetText(Service, this, "nhs_associateantigenoncreate_m");
}
/// <summary>
/// Retrieves the current value's text in the user's language.
/// </summary>
/// <param name="AttributeMetadata">The attribute metadata previously retrieved using the 'GetAttributeMetadata' extension method on the IOrganizationService object.</param>
/// <returns></returns>
public string AssociateAntigenOnCreate_M_Text(EnumAttributeMetadata AttributeMetadata)
{
	return AttributeMetadata.GetOptionSetText(this.AssociateAntigenOnCreate_M_OptionSetValue.Value);
}
/// <summary>
///Logical Name: nhs_associateantigenoncreate_n
/// </summary>
[AttributeLogicalNameAttribute("nhs_associateantigenoncreate_n")]
public eAntigenResult_SourceContext? AssociateAntigenOnCreate_N
{
	get
	{
		if (AssociateAntigenOnCreate_N_OptionSetValue != null) { return (eAntigenResult_SourceContext)AssociateAntigenOnCreate_N_OptionSetValue.Value; }
		return null;
	}
	set
	{
		if (value != null) { this.AssociateAntigenOnCreate_N_OptionSetValue = new OptionSetValue((int)value); }
		else this.AssociateAntigenOnCreate_N_OptionSetValue = null;
	}
}
///<summary>
///<para>Logical Name: nhs_associateantigenoncreate_n</para>
///</summary>
[AttributeLogicalNameAttribute("nhs_associateantigenoncreate_n")]
public OptionSetValue AssociateAntigenOnCreate_N_OptionSetValue
{
	get { return this.GetPropertyValue<OptionSetValue>("nhs_associateantigenoncreate_n"); }
	set { this.SetPropertyValue<OptionSetValue>("nhs_associateantigenoncreate_n", value, "AssociateAntigenOnCreate_N_OptionSetValue"); }
}
/// <summary>
/// Retrieves the current value's text in the user's language.
/// </summary>
/// <param name="Service">CRM Organization Service</param>
/// <returns></returns>
public string AssociateAntigenOnCreate_N_Text(IOrganizationService Service)
{
	return this.AssociateAntigenOnCreate_N_OptionSetValue.GetOptionSetText(Service, this, "nhs_associateantigenoncreate_n");
}
/// <summary>
/// Retrieves the current value's text in the user's language.
/// </summary>
/// <param name="AttributeMetadata">The attribute metadata previously retrieved using the 'GetAttributeMetadata' extension method on the IOrganizationService object.</param>
/// <returns></returns>
public string AssociateAntigenOnCreate_N_Text(EnumAttributeMetadata AttributeMetadata)
{
	return AttributeMetadata.GetOptionSetText(this.AssociateAntigenOnCreate_N_OptionSetValue.Value);
}
/// <summary>
///Logical Name: nhs_associateantigenoncreate_smalls
/// </summary>
[AttributeLogicalNameAttribute("nhs_associateantigenoncreate_smalls")]
public eAntigenResult_SourceContext? AssociateAntigenOnCreate_S
{
	get
	{
		if (AssociateAntigenOnCreate_S_OptionSetValue != null) { return (eAntigenResult_SourceContext)AssociateAntigenOnCreate_S_OptionSetValue.Value; }
		return null;
	}
	set
	{
		if (value != null) { this.AssociateAntigenOnCreate_S_OptionSetValue = new OptionSetValue((int)value); }
		else this.AssociateAntigenOnCreate_S_OptionSetValue = null;
	}
}
///<summary>
///<para>Logical Name: nhs_associateantigenoncreate_smalls</para>
///</summary>
[AttributeLogicalNameAttribute("nhs_associateantigenoncreate_smalls")]
public OptionSetValue AssociateAntigenOnCreate_S_OptionSetValue
{
	get { return this.GetPropertyValue<OptionSetValue>("nhs_associateantigenoncreate_smalls"); }
	set { this.SetPropertyValue<OptionSetValue>("nhs_associateantigenoncreate_smalls", value, "AssociateAntigenOnCreate_S_OptionSetValue"); }
}
/// <summary>
/// Retrieves the current value's text in the user's language.
/// </summary>
/// <param name="Service">CRM Organization Service</param>
/// <returns></returns>
public string AssociateAntigenOnCreate_S_Text(IOrganizationService Service)
{
	return this.AssociateAntigenOnCreate_S_OptionSetValue.GetOptionSetText(Service, this, "nhs_associateantigenoncreate_smalls");
}
/// <summary>
/// Retrieves the current value's text in the user's language.
/// </summary>
/// <param name="AttributeMetadata">The attribute metadata previously retrieved using the 'GetAttributeMetadata' extension method on the IOrganizationService object.</param>
/// <returns></returns>
public string AssociateAntigenOnCreate_S_Text(EnumAttributeMetadata AttributeMetadata)
{
	return AttributeMetadata.GetOptionSetText(this.AssociateAntigenOnCreate_S_OptionSetValue.Value);
}
/// <summary>
///Logical Name: nhs_associateantigenoncreate_bigs
/// </summary>
[AttributeLogicalNameAttribute("nhs_associateantigenoncreate_bigs")]
public eAntigenResult_SourceContext? AssociateAntigenOnCreate_S2
{
	get
	{
		if (AssociateAntigenOnCreate_S2_OptionSetValue != null) { return (eAntigenResult_SourceContext)AssociateAntigenOnCreate_S2_OptionSetValue.Value; }
		return null;
	}
	set
	{
		if (value != null) { this.AssociateAntigenOnCreate_S2_OptionSetValue = new OptionSetValue((int)value); }
		else this.AssociateAntigenOnCreate_S2_OptionSetValue = null;
	}
}
///<summary>
///<para>Logical Name: nhs_associateantigenoncreate_bigs</para>
///</summary>
[AttributeLogicalNameAttribute("nhs_associateantigenoncreate_bigs")]
public OptionSetValue AssociateAntigenOnCreate_S2_OptionSetValue
{
	get { return this.GetPropertyValue<OptionSetValue>("nhs_associateantigenoncreate_bigs"); }
	set { this.SetPropertyValue<OptionSetValue>("nhs_associateantigenoncreate_bigs", value, "AssociateAntigenOnCreate_S2_OptionSetValue"); }
}
/// <summary>
/// Retrieves the current value's text in the user's language.
/// </summary>
/// <param name="Service">CRM Organization Service</param>
/// <returns></returns>
public string AssociateAntigenOnCreate_S2_Text(IOrganizationService Service)
{
	return this.AssociateAntigenOnCreate_S2_OptionSetValue.GetOptionSetText(Service, this, "nhs_associateantigenoncreate_bigs");
}
/// <summary>
/// Retrieves the current value's text in the user's language.
/// </summary>
/// <param name="AttributeMetadata">The attribute metadata previously retrieved using the 'GetAttributeMetadata' extension method on the IOrganizationService object.</param>
/// <returns></returns>
public string AssociateAntigenOnCreate_S2_Text(EnumAttributeMetadata AttributeMetadata)
{
	return AttributeMetadata.GetOptionSetText(this.AssociateAntigenOnCreate_S2_OptionSetValue.Value);
}
///<summary>
///<para>Logical Name: nhs_contributorcode</para>
///<para>Max Length: 50 characters</para>
///</summary>
[AttributeLogicalNameAttribute("nhs_contributorcode")]
public string ContributorCode
{
	get { return this.GetPropertyValue<string>("nhs_contributorcode"); }
	set { this.SetPropertyValue("nhs_contributorcode", value, 50, "ContributorCode"); }
}
///<summary>
///<para>Logical Name: createdby</para>
///</summary>
[AttributeLogicalNameAttribute("createdby")]
public EntityReference CreatedBy
{
	get { return this.GetPropertyValue<EntityReference>("createdby"); }
}
///<summary>
///<para>Logical Name: createdonbehalfby</para>
///</summary>
[AttributeLogicalNameAttribute("createdonbehalfby")]
public EntityReference CreatedBy_Delegate
{
	get { return this.GetPropertyValue<EntityReference>("createdonbehalfby"); }
}
///<summary>
///<para>Logical Name: createdon</para>
///</summary>
[AttributeLogicalNameAttribute("createdon")]
public DateTime? CreatedOn
{
	get { return this.GetPropertyValue<DateTime?>("createdon"); }
}
///<summary>
///<para>Logical Name: nhs_donorcount</para>
///<para>Minimum Value: 0</para>
///<para>Maximum Value: 2147483647</para>
///</summary>
[AttributeLogicalNameAttribute("nhs_donorcount")]
public int? DonorCount
{
	get { return this.GetPropertyValue<int?>("nhs_donorcount"); }
	set { this.SetPropertyValue("nhs_donorcount", (int?)value, (int)0, (int)2147483647, "DonorCount"); }
}
///<summary>
///<para>Logical Name: nhs_frozenunitcount</para>
///<para>Minimum Value: 0</para>
///<para>Maximum Value: 2147483647</para>
///</summary>
[AttributeLogicalNameAttribute("nhs_frozenunitcount")]
public int? FrozenUnitCount
{
	get { return this.GetPropertyValue<int?>("nhs_frozenunitcount"); }
	set { this.SetPropertyValue("nhs_frozenunitcount", (int?)value, (int)0, (int)2147483647, "FrozenUnitCount"); }
}
///<summary>
///<para>Logical Name: nhs_headerrow</para>
///<para>Max Length: 1000 characters</para>
///</summary>
[AttributeLogicalNameAttribute("nhs_headerrow")]
public string HeaderRow
{
	get { return this.GetPropertyValue<string>("nhs_headerrow"); }
	set { this.SetPropertyValue("nhs_headerrow", value, 1000, "HeaderRow"); }
}
///<summary>
///<para>Logical Name: importsequencenumber</para>
///<para>Minimum Value: -2147483648</para>
///<para>Maximum Value: 2147483647</para>
///</summary>
[AttributeLogicalNameAttribute("importsequencenumber")]
public int? ImportSequenceNumber
{
	get { return this.GetPropertyValue<int?>("importsequencenumber"); }
	set { this.SetPropertyValue("importsequencenumber", (int?)value, (int)-2147483648, (int)2147483647, "ImportSequenceNumber"); }
}
///<summary>
///<para>Logical Name: nhs_lastreviewedon</para>
///</summary>
[AttributeLogicalNameAttribute("nhs_lastreviewedon")]
public DateTime? LastReviewedOn
{
	get { return this.GetPropertyValue<DateTime?>("nhs_lastreviewedon"); }
	set { this.SetPropertyValue<DateTime?>("nhs_lastreviewedon", value, "LastReviewedOn"); }
}
///<summary>
///<para>Logical Name: modifiedby</para>
///</summary>
[AttributeLogicalNameAttribute("modifiedby")]
public EntityReference ModifiedBy
{
	get { return this.GetPropertyValue<EntityReference>("modifiedby"); }
}
///<summary>
///<para>Logical Name: modifiedonbehalfby</para>
///</summary>
[AttributeLogicalNameAttribute("modifiedonbehalfby")]
public EntityReference ModifiedBy_Delegate
{
	get { return this.GetPropertyValue<EntityReference>("modifiedonbehalfby"); }
}
///<summary>
///<para>Logical Name: modifiedon</para>
///</summary>
[AttributeLogicalNameAttribute("modifiedon")]
public DateTime? ModifiedOn
{
	get { return this.GetPropertyValue<DateTime?>("modifiedon"); }
}
///<summary>
///<para>Logical Name: ownerid</para>
///</summary>
[AttributeLogicalNameAttribute("ownerid")]
public EntityReference Owner
{
	get { return this.GetPropertyValue<EntityReference>("ownerid"); }
	set { this.SetPropertyValue<EntityReference>("ownerid", value, "Owner"); }
}
///<summary>
///<para>Logical Name: owningbusinessunit</para>
///</summary>
[AttributeLogicalNameAttribute("owningbusinessunit")]
public EntityReference OwningBusinessUnit
{
	get { return this.GetPropertyValue<EntityReference>("owningbusinessunit"); }
}
///<summary>
///<para>Logical Name: owningteam</para>
///</summary>
[AttributeLogicalNameAttribute("owningteam")]
public EntityReference OwningTeam
{
	get { return this.GetPropertyValue<EntityReference>("owningteam"); }
}
///<summary>
///<para>Logical Name: owninguser</para>
///</summary>
[AttributeLogicalNameAttribute("owninguser")]
public EntityReference OwningUser
{
	get { return this.GetPropertyValue<EntityReference>("owninguser"); }
}
///<summary>
///<para>Logical Name: nhs_panelcode</para>
///<para>Max Length: 10 characters</para>
///</summary>
[AttributeLogicalNameAttribute("nhs_panelcode")]
public string PanelCode
{
	get { return this.GetPropertyValue<string>("nhs_panelcode"); }
	set { this.SetPropertyValue("nhs_panelcode", value, 10, "PanelCode"); }
}
///<summary>
///<para>Logical Name: nhs_parentaccount</para>
///</summary>
[AttributeLogicalNameAttribute("nhs_parentaccount")]
public EntityReference ParentAccount
{
	get { return this.GetPropertyValue<EntityReference>("nhs_parentaccount"); }
	set { this.SetPropertyValue<EntityReference>("nhs_parentaccount", value, "ParentAccount"); }
}
///<summary>
///<para>Key Property (Uniqueidentifier)</para>
///<para>Logical Name: nhs_rarebloodsourceid</para>
///</summary>
[AttributeLogicalNameAttribute("nhs_rarebloodsourceid")]
public Guid RareBloodSourceId
{
	get
	{
		return base.Id;
	}
	set
	{
		base.Id = value;
		base.SetPropertyValue("nhs_rarebloodsourceid", value, "RareBloodSourceId");
	}
}
///<summary>
///<para>Logical Name: nhs_rawdata</para>
///<para>Max Length: 1000 characters</para>
///</summary>
[AttributeLogicalNameAttribute("nhs_rawdata")]
public string Rawdata
{
	get { return this.GetPropertyValue<string>("nhs_rawdata"); }
	set { this.SetPropertyValue("nhs_rawdata", value, 1000, "Rawdata"); }
}
///<summary>
///<para>Logical Name: overriddencreatedon</para>
///</summary>
[AttributeLogicalNameAttribute("overriddencreatedon")]
public DateTime? RecordCreatedOn
{
	get { return this.GetPropertyValue<DateTime?>("overriddencreatedon"); }
	set { this.SetPropertyValue<DateTime?>("overriddencreatedon", value, "RecordCreatedOn"); }
}
///<summary>
///<para>Logical Name: nhs_sourcetype</para>
///<para>True = Rare Frozen Unit Product Line</para>
///<para>False = Individual Donor</para>
///</summary>
[AttributeLogicalNameAttribute("nhs_sourcetype")]
public bool? SourceType
{
	get { return this.GetPropertyValue<bool?>("nhs_sourcetype"); }
	set { this.SetPropertyValue<bool?>("nhs_sourcetype", value, "SourceType"); }
}
/// <summary>
///Logical Name: statecode
/// </summary>
[AttributeLogicalNameAttribute("statecode")]
public eStatus? Status
{
	get
	{
		if (Status_OptionSetValue != null) { return (eStatus)Status_OptionSetValue.Value; }
		return null;
	}
	set
	{
		if (value != null) { this.Status_OptionSetValue = new OptionSetValue((int)value); }
		else this.Status_OptionSetValue = null;
	}
}
///<summary>
///<para>Logical Name: statecode</para>
///</summary>
[AttributeLogicalNameAttribute("statecode")]
public OptionSetValue Status_OptionSetValue
{
	get { return this.GetPropertyValue<OptionSetValue>("statecode"); }
	set { this.SetPropertyValue<OptionSetValue>("statecode", value, "Status_OptionSetValue"); }
}
/// <summary>
/// Retrieves the current value's text in the user's language.
/// </summary>
/// <param name="Service">CRM Organization Service</param>
/// <returns></returns>
public string Status_Text(IOrganizationService Service)
{
	return this.Status_OptionSetValue.GetOptionSetText(Service, this, "statecode");
}
/// <summary>
/// Retrieves the current value's text in the user's language.
/// </summary>
/// <param name="AttributeMetadata">The attribute metadata previously retrieved using the 'GetAttributeMetadata' extension method on the IOrganizationService object.</param>
/// <returns></returns>
public string Status_Text(EnumAttributeMetadata AttributeMetadata)
{
	return AttributeMetadata.GetOptionSetText(this.Status_OptionSetValue.Value);
}
/// <summary>
///Logical Name: statuscode
/// </summary>
[AttributeLogicalNameAttribute("statuscode")]
public eStatusReason? StatusReason
{
	get
	{
		if (StatusReason_OptionSetValue != null) { return (eStatusReason)StatusReason_OptionSetValue.Value; }
		return null;
	}
	set
	{
		if (value != null) { this.StatusReason_OptionSetValue = new OptionSetValue((int)value); }
		else this.StatusReason_OptionSetValue = null;
	}
}
///<summary>
///<para>Logical Name: statuscode</para>
///</summary>
[AttributeLogicalNameAttribute("statuscode")]
public OptionSetValue StatusReason_OptionSetValue
{
	get { return this.GetPropertyValue<OptionSetValue>("statuscode"); }
	set { this.SetPropertyValue<OptionSetValue>("statuscode", value, "StatusReason_OptionSetValue"); }
}
/// <summary>
/// Retrieves the current value's text in the user's language.
/// </summary>
/// <param name="Service">CRM Organization Service</param>
/// <returns></returns>
public string StatusReason_Text(IOrganizationService Service)
{
	return this.StatusReason_OptionSetValue.GetOptionSetText(Service, this, "statuscode");
}
/// <summary>
/// Retrieves the current value's text in the user's language.
/// </summary>
/// <param name="AttributeMetadata">The attribute metadata previously retrieved using the 'GetAttributeMetadata' extension method on the IOrganizationService object.</param>
/// <returns></returns>
public string StatusReason_Text(EnumAttributeMetadata AttributeMetadata)
{
	return AttributeMetadata.GetOptionSetText(this.StatusReason_OptionSetValue.Value);
}
///<summary>
///<para>Logical Name: timezoneruleversionnumber</para>
///<para>Minimum Value: -1</para>
///<para>Maximum Value: 2147483647</para>
///</summary>
[AttributeLogicalNameAttribute("timezoneruleversionnumber")]
public int? TimeZoneRuleVersionNumber
{
	get { return this.GetPropertyValue<int?>("timezoneruleversionnumber"); }
	set { this.SetPropertyValue("timezoneruleversionnumber", (int?)value, (int)-1, (int)2147483647, "TimeZoneRuleVersionNumber"); }
}
///<summary>
///<para>Logical Name: utcconversiontimezonecode</para>
///<para>Minimum Value: -1</para>
///<para>Maximum Value: 2147483647</para>
///</summary>
[AttributeLogicalNameAttribute("utcconversiontimezonecode")]
public int? UTCConversionTimeZoneCode
{
	get { return this.GetPropertyValue<int?>("utcconversiontimezonecode"); }
	set { this.SetPropertyValue("utcconversiontimezonecode", (int?)value, (int)-1, (int)2147483647, "UTCConversionTimeZoneCode"); }
}
///<summary>
///<para>Logical Name: versionnumber</para>
///</summary>
[AttributeLogicalNameAttribute("versionnumber")]
public int? VersionNumber
{
	get { return this.GetPropertyValue<int?>("versionnumber"); }
}


        /// <summary>
/// <para><b>Entity ()</b></para>
/// <para>Schema Name: nhs_rarebloodsource_ActivityPointers</para>
/// </summary>
public List<Entity> GetActivities (IOrganizationService Service, params string[] Columns) { return BaseProxyClass.GetRelatedOneToManyEntities(Service, this.Id, "activitypointer", "regardingobjectid", Columns); }
/// <summary>
/// <para><b>Entity ()</b></para>
/// <para>Schema Name: nhs_rarebloodsource_ActivityPointers</para>
/// </summary>
public List<Entity> GetActivities (IOrganizationService Service, ColumnSet Columns) { return BaseProxyClass.GetRelatedOneToManyEntities(Service, this.Id, "activitypointer", "regardingobjectid", Columns); }
/// <summary>
/// <para><b>Entity ()</b></para>
/// <para>Schema Name: nhs_rarebloodsource_Appointments</para>
/// </summary>
public List<Entity> GetAppointments (IOrganizationService Service, params string[] Columns) { return BaseProxyClass.GetRelatedOneToManyEntities(Service, this.Id, "appointment", "regardingobjectid", Columns); }
/// <summary>
/// <para><b>Entity ()</b></para>
/// <para>Schema Name: nhs_rarebloodsource_Appointments</para>
/// </summary>
public List<Entity> GetAppointments (IOrganizationService Service, ColumnSet Columns) { return BaseProxyClass.GetRelatedOneToManyEntities(Service, this.Id, "appointment", "regardingobjectid", Columns); }
/// <summary>
/// <para><b>Entity ()</b></para>
/// <para>Schema Name: nhs_rarebloodsource_AsyncOperations</para>
/// </summary>
public List<Entity> GetSystemJobs (IOrganizationService Service, params string[] Columns) { return BaseProxyClass.GetRelatedOneToManyEntities(Service, this.Id, "asyncoperation", "regardingobjectid", Columns); }
/// <summary>
/// <para><b>Entity ()</b></para>
/// <para>Schema Name: nhs_rarebloodsource_AsyncOperations</para>
/// </summary>
public List<Entity> GetSystemJobs (IOrganizationService Service, ColumnSet Columns) { return BaseProxyClass.GetRelatedOneToManyEntities(Service, this.Id, "asyncoperation", "regardingobjectid", Columns); }
/// <summary>
/// <para><b>Entity ()</b></para>
/// <para>Schema Name: nhs_rarebloodsource_BulkDeleteFailures</para>
/// </summary>
public List<Entity> GetBulkDeleteFailures (IOrganizationService Service, params string[] Columns) { return BaseProxyClass.GetRelatedOneToManyEntities(Service, this.Id, "bulkdeletefailure", "regardingobjectid", Columns); }
/// <summary>
/// <para><b>Entity ()</b></para>
/// <para>Schema Name: nhs_rarebloodsource_BulkDeleteFailures</para>
/// </summary>
public List<Entity> GetBulkDeleteFailures (IOrganizationService Service, ColumnSet Columns) { return BaseProxyClass.GetRelatedOneToManyEntities(Service, this.Id, "bulkdeletefailure", "regardingobjectid", Columns); }
/// <summary>
/// <para><b>Entity ()</b></para>
/// <para>Schema Name: nhs_rarebloodsource_DuplicateBaseRecord</para>
/// </summary>
public List<Entity> GetDuplicateRecords (IOrganizationService Service, params string[] Columns) { return BaseProxyClass.GetRelatedOneToManyEntities(Service, this.Id, "duplicaterecord", "baserecordid", Columns); }
/// <summary>
/// <para><b>Entity ()</b></para>
/// <para>Schema Name: nhs_rarebloodsource_DuplicateBaseRecord</para>
/// </summary>
public List<Entity> GetDuplicateRecords (IOrganizationService Service, ColumnSet Columns) { return BaseProxyClass.GetRelatedOneToManyEntities(Service, this.Id, "duplicaterecord", "baserecordid", Columns); }
/// <summary>
/// <para><b>Entity ()</b></para>
/// <para>Schema Name: nhs_rarebloodsource_DuplicateMatchingRecord</para>
/// </summary>
public List<Entity> GetDuplicateRecords2 (IOrganizationService Service, params string[] Columns) { return BaseProxyClass.GetRelatedOneToManyEntities(Service, this.Id, "duplicaterecord", "duplicaterecordid", Columns); }
/// <summary>
/// <para><b>Entity ()</b></para>
/// <para>Schema Name: nhs_rarebloodsource_DuplicateMatchingRecord</para>
/// </summary>
public List<Entity> GetDuplicateRecords2 (IOrganizationService Service, ColumnSet Columns) { return BaseProxyClass.GetRelatedOneToManyEntities(Service, this.Id, "duplicaterecord", "duplicaterecordid", Columns); }
/// <summary>
/// <para><b>Entity ()</b></para>
/// <para>Schema Name: nhs_rarebloodsource_Emails</para>
/// </summary>
public List<Entity> GetEmailMessages (IOrganizationService Service, params string[] Columns) { return BaseProxyClass.GetRelatedOneToManyEntities(Service, this.Id, "email", "regardingobjectid", Columns); }
/// <summary>
/// <para><b>Entity ()</b></para>
/// <para>Schema Name: nhs_rarebloodsource_Emails</para>
/// </summary>
public List<Entity> GetEmailMessages (IOrganizationService Service, ColumnSet Columns) { return BaseProxyClass.GetRelatedOneToManyEntities(Service, this.Id, "email", "regardingobjectid", Columns); }
/// <summary>
/// <para><b>Entity ()</b></para>
/// <para>Schema Name: nhs_rarebloodsource_Faxes</para>
/// </summary>
public List<Entity> GetFaxes (IOrganizationService Service, params string[] Columns) { return BaseProxyClass.GetRelatedOneToManyEntities(Service, this.Id, "fax", "regardingobjectid", Columns); }
/// <summary>
/// <para><b>Entity ()</b></para>
/// <para>Schema Name: nhs_rarebloodsource_Faxes</para>
/// </summary>
public List<Entity> GetFaxes (IOrganizationService Service, ColumnSet Columns) { return BaseProxyClass.GetRelatedOneToManyEntities(Service, this.Id, "fax", "regardingobjectid", Columns); }
/// <summary>
/// <para><b>Entity ()</b></para>
/// <para>Schema Name: nhs_rarebloodsource_Letters</para>
/// </summary>
public List<Entity> GetLetters (IOrganizationService Service, params string[] Columns) { return BaseProxyClass.GetRelatedOneToManyEntities(Service, this.Id, "letter", "regardingobjectid", Columns); }
/// <summary>
/// <para><b>Entity ()</b></para>
/// <para>Schema Name: nhs_rarebloodsource_Letters</para>
/// </summary>
public List<Entity> GetLetters (IOrganizationService Service, ColumnSet Columns) { return BaseProxyClass.GetRelatedOneToManyEntities(Service, this.Id, "letter", "regardingobjectid", Columns); }
/// <summary>
/// <para><b>Entity ()</b></para>
/// <para>Schema Name: nhs_rarebloodsource_MailboxTrackingFolders</para>
/// </summary>
public List<Entity> GetMailboxAutoTrackingFolders (IOrganizationService Service, params string[] Columns) { return BaseProxyClass.GetRelatedOneToManyEntities(Service, this.Id, "mailboxtrackingfolder", "regardingobjectid", Columns); }
/// <summary>
/// <para><b>Entity ()</b></para>
/// <para>Schema Name: nhs_rarebloodsource_MailboxTrackingFolders</para>
/// </summary>
public List<Entity> GetMailboxAutoTrackingFolders (IOrganizationService Service, ColumnSet Columns) { return BaseProxyClass.GetRelatedOneToManyEntities(Service, this.Id, "mailboxtrackingfolder", "regardingobjectid", Columns); }
/// <summary>
/// <para><b>Entity ()</b></para>
/// <para>Schema Name: nhs_rarebloodsource_msdyn_comments</para>
/// </summary>
public List<Entity> GetComments (IOrganizationService Service, params string[] Columns) { return BaseProxyClass.GetRelatedOneToManyEntities(Service, this.Id, "msdyn_comment", "regardingobjectid", Columns); }
/// <summary>
/// <para><b>Entity ()</b></para>
/// <para>Schema Name: nhs_rarebloodsource_msdyn_comments</para>
/// </summary>
public List<Entity> GetComments (IOrganizationService Service, ColumnSet Columns) { return BaseProxyClass.GetRelatedOneToManyEntities(Service, this.Id, "msdyn_comment", "regardingobjectid", Columns); }
/// <summary>
/// <para><b>Entity ()</b></para>
/// <para>Schema Name: nhs_rarebloodsource_msfp_surveyinvites</para>
/// </summary>
public List<Entity> GetFormsProSurveyInvites (IOrganizationService Service, params string[] Columns) { return BaseProxyClass.GetRelatedOneToManyEntities(Service, this.Id, "msfp_surveyinvite", "regardingobjectid", Columns); }
/// <summary>
/// <para><b>Entity ()</b></para>
/// <para>Schema Name: nhs_rarebloodsource_msfp_surveyinvites</para>
/// </summary>
public List<Entity> GetFormsProSurveyInvites (IOrganizationService Service, ColumnSet Columns) { return BaseProxyClass.GetRelatedOneToManyEntities(Service, this.Id, "msfp_surveyinvite", "regardingobjectid", Columns); }
/// <summary>
/// <para><b>Entity ()</b></para>
/// <para>Schema Name: nhs_rarebloodsource_msfp_surveyresponses</para>
/// </summary>
public List<Entity> GetFormsProSurveyResponses (IOrganizationService Service, params string[] Columns) { return BaseProxyClass.GetRelatedOneToManyEntities(Service, this.Id, "msfp_surveyresponse", "regardingobjectid", Columns); }
/// <summary>
/// <para><b>Entity ()</b></para>
/// <para>Schema Name: nhs_rarebloodsource_msfp_surveyresponses</para>
/// </summary>
public List<Entity> GetFormsProSurveyResponses (IOrganizationService Service, ColumnSet Columns) { return BaseProxyClass.GetRelatedOneToManyEntities(Service, this.Id, "msfp_surveyresponse", "regardingobjectid", Columns); }
/// <summary>
/// <para><b>Antigen_SourceAssociation (Source)</b></para>
/// <para>Schema Name: nhs_nhs_rarebloodsource_nhs_antigensourceassociation_SourceId</para>
/// </summary>
public List<Antigen_SourceAssociation> GetAntigen_SourceAssociations_Source (IOrganizationService Service, params string[] Columns) { return BaseProxyClass.GetRelatedOneToManyEntities<Antigen_SourceAssociation>(Service, this.Id, "nhs_antigensourceassociation", "nhs_sourceid", Columns); }
/// <summary>
/// <para><b>Antigen_SourceAssociation (Source)</b></para>
/// <para>Schema Name: nhs_nhs_rarebloodsource_nhs_antigensourceassociation_SourceId</para>
/// </summary>
public List<Antigen_SourceAssociation> GetAntigen_SourceAssociations_Source (IOrganizationService Service, ColumnSet Columns) { return BaseProxyClass.GetRelatedOneToManyEntities<Antigen_SourceAssociation>(Service, this.Id, "nhs_antigensourceassociation", "nhs_sourceid", Columns); }
/// <summary>
/// <para><b>Rarity_SourceAssociation (Source)</b></para>
/// <para>Schema Name: nhs_nhs_rarebloodsource_nhs_raritysourceassociation_SourceId</para>
/// </summary>
public List<Rarity_SourceAssociation> GetRarity_SourceAssociations_Source (IOrganizationService Service, params string[] Columns) { return BaseProxyClass.GetRelatedOneToManyEntities<Rarity_SourceAssociation>(Service, this.Id, "nhs_raritysourceassociation", "nhs_sourceid", Columns); }
/// <summary>
/// <para><b>Rarity_SourceAssociation (Source)</b></para>
/// <para>Schema Name: nhs_nhs_rarebloodsource_nhs_raritysourceassociation_SourceId</para>
/// </summary>
public List<Rarity_SourceAssociation> GetRarity_SourceAssociations_Source (IOrganizationService Service, ColumnSet Columns) { return BaseProxyClass.GetRelatedOneToManyEntities<Rarity_SourceAssociation>(Service, this.Id, "nhs_raritysourceassociation", "nhs_sourceid", Columns); }
/// <summary>
/// <para><b>Entity ()</b></para>
/// <para>Schema Name: nhs_rarebloodsource_PhoneCalls</para>
/// </summary>
public List<Entity> GetPhoneCalls (IOrganizationService Service, params string[] Columns) { return BaseProxyClass.GetRelatedOneToManyEntities(Service, this.Id, "phonecall", "regardingobjectid", Columns); }
/// <summary>
/// <para><b>Entity ()</b></para>
/// <para>Schema Name: nhs_rarebloodsource_PhoneCalls</para>
/// </summary>
public List<Entity> GetPhoneCalls (IOrganizationService Service, ColumnSet Columns) { return BaseProxyClass.GetRelatedOneToManyEntities(Service, this.Id, "phonecall", "regardingobjectid", Columns); }
/// <summary>
/// <para><b>Entity ()</b></para>
/// <para>Schema Name: nhs_rarebloodsource_PrincipalObjectAttributeAccesses</para>
/// </summary>
public List<Entity> GetFieldSharing (IOrganizationService Service, params string[] Columns) { return BaseProxyClass.GetRelatedOneToManyEntities(Service, this.Id, "principalobjectattributeaccess", "objectid", Columns); }
/// <summary>
/// <para><b>Entity ()</b></para>
/// <para>Schema Name: nhs_rarebloodsource_PrincipalObjectAttributeAccesses</para>
/// </summary>
public List<Entity> GetFieldSharing (IOrganizationService Service, ColumnSet Columns) { return BaseProxyClass.GetRelatedOneToManyEntities(Service, this.Id, "principalobjectattributeaccess", "objectid", Columns); }
/// <summary>
/// <para><b>Entity ()</b></para>
/// <para>Schema Name: nhs_rarebloodsource_ProcessSession</para>
/// </summary>
public List<Entity> GetProcessSessions (IOrganizationService Service, params string[] Columns) { return BaseProxyClass.GetRelatedOneToManyEntities(Service, this.Id, "processsession", "regardingobjectid", Columns); }
/// <summary>
/// <para><b>Entity ()</b></para>
/// <para>Schema Name: nhs_rarebloodsource_ProcessSession</para>
/// </summary>
public List<Entity> GetProcessSessions (IOrganizationService Service, ColumnSet Columns) { return BaseProxyClass.GetRelatedOneToManyEntities(Service, this.Id, "processsession", "regardingobjectid", Columns); }
/// <summary>
/// <para><b>Entity ()</b></para>
/// <para>Schema Name: nhs_rarebloodsource_RecurringAppointmentMasters</para>
/// </summary>
public List<Entity> GetRecurringAppointments (IOrganizationService Service, params string[] Columns) { return BaseProxyClass.GetRelatedOneToManyEntities(Service, this.Id, "recurringappointmentmaster", "regardingobjectid", Columns); }
/// <summary>
/// <para><b>Entity ()</b></para>
/// <para>Schema Name: nhs_rarebloodsource_RecurringAppointmentMasters</para>
/// </summary>
public List<Entity> GetRecurringAppointments (IOrganizationService Service, ColumnSet Columns) { return BaseProxyClass.GetRelatedOneToManyEntities(Service, this.Id, "recurringappointmentmaster", "regardingobjectid", Columns); }
/// <summary>
/// <para><b>Entity ()</b></para>
/// <para>Schema Name: nhs_rarebloodsource_ServiceAppointments</para>
/// </summary>
public List<Entity> GetServiceActivities (IOrganizationService Service, params string[] Columns) { return BaseProxyClass.GetRelatedOneToManyEntities(Service, this.Id, "serviceappointment", "regardingobjectid", Columns); }
/// <summary>
/// <para><b>Entity ()</b></para>
/// <para>Schema Name: nhs_rarebloodsource_ServiceAppointments</para>
/// </summary>
public List<Entity> GetServiceActivities (IOrganizationService Service, ColumnSet Columns) { return BaseProxyClass.GetRelatedOneToManyEntities(Service, this.Id, "serviceappointment", "regardingobjectid", Columns); }
/// <summary>
/// <para><b>Entity ()</b></para>
/// <para>Schema Name: nhs_rarebloodsource_SocialActivities</para>
/// </summary>
public List<Entity> GetSocialActivities (IOrganizationService Service, params string[] Columns) { return BaseProxyClass.GetRelatedOneToManyEntities(Service, this.Id, "socialactivity", "regardingobjectid", Columns); }
/// <summary>
/// <para><b>Entity ()</b></para>
/// <para>Schema Name: nhs_rarebloodsource_SocialActivities</para>
/// </summary>
public List<Entity> GetSocialActivities (IOrganizationService Service, ColumnSet Columns) { return BaseProxyClass.GetRelatedOneToManyEntities(Service, this.Id, "socialactivity", "regardingobjectid", Columns); }
/// <summary>
/// <para><b>Entity ()</b></para>
/// <para>Schema Name: nhs_rarebloodsource_SyncErrors</para>
/// </summary>
public List<Entity> GetSyncErrors (IOrganizationService Service, params string[] Columns) { return BaseProxyClass.GetRelatedOneToManyEntities(Service, this.Id, "syncerror", "regardingobjectid", Columns); }
/// <summary>
/// <para><b>Entity ()</b></para>
/// <para>Schema Name: nhs_rarebloodsource_SyncErrors</para>
/// </summary>
public List<Entity> GetSyncErrors (IOrganizationService Service, ColumnSet Columns) { return BaseProxyClass.GetRelatedOneToManyEntities(Service, this.Id, "syncerror", "regardingobjectid", Columns); }
/// <summary>
/// <para><b>Task (Regarding)</b></para>
/// <para>Schema Name: nhs_rarebloodsource_Tasks</para>
/// </summary>
public List<Task> GetTasks_Regarding (IOrganizationService Service, params string[] Columns) { return BaseProxyClass.GetRelatedOneToManyEntities<Task>(Service, this.Id, "task", "regardingobjectid", Columns); }
/// <summary>
/// <para><b>Task (Regarding)</b></para>
/// <para>Schema Name: nhs_rarebloodsource_Tasks</para>
/// </summary>
public List<Task> GetTasks_Regarding (IOrganizationService Service, ColumnSet Columns) { return BaseProxyClass.GetRelatedOneToManyEntities<Task>(Service, this.Id, "task", "regardingobjectid", Columns); }
/// <summary>
/// <para><b>Entity ()</b></para>
/// <para>Schema Name: nhs_rarebloodsource_UserEntityInstanceDatas</para>
/// </summary>
public List<Entity> GetUserEntityInstanceData (IOrganizationService Service, params string[] Columns) { return BaseProxyClass.GetRelatedOneToManyEntities(Service, this.Id, "userentityinstancedata", "objectid", Columns); }
/// <summary>
/// <para><b>Entity ()</b></para>
/// <para>Schema Name: nhs_rarebloodsource_UserEntityInstanceDatas</para>
/// </summary>
public List<Entity> GetUserEntityInstanceData (IOrganizationService Service, ColumnSet Columns) { return BaseProxyClass.GetRelatedOneToManyEntities(Service, this.Id, "userentityinstancedata", "objectid", Columns); }


        

        

        public enum eABOSub_types
{
	///<summary><para>A</para>
	///<para>Value = 127130000</para></summary>
	[Description("A")]
	A = 127130000, 
	///<summary><para>A1</para>
	///<para>Value = 127130001</para></summary>
	[Description("A1")]
	A1 = 127130001, 
	///<summary><para>A1B</para>
	///<para>Value = 127130002</para></summary>
	[Description("A1B")]
	A1B = 127130002, 
	///<summary><para>A2</para>
	///<para>Value = 127130003</para></summary>
	[Description("A2")]
	A2 = 127130003, 
	///<summary><para>A2B</para>
	///<para>Value = 127130004</para></summary>
	[Description("A2B")]
	A2B = 127130004, 
	///<summary><para>AB</para>
	///<para>Value = 127130005</para></summary>
	[Description("AB")]
	AB = 127130005, 
	///<summary><para>B</para>
	///<para>Value = 127130006</para></summary>
	[Description("B")]
	B = 127130006, 
	///<summary><para>O</para>
	///<para>Value = 127130007</para></summary>
	[Description("O")]
	O = 127130007, 
	///<summary><para>Oh</para>
	///<para>Value = 127130008</para></summary>
	[Description("Oh")]
	Oh = 127130008
}
public enum eAntigenResult_SourceContext
{
	///<summary><para>+</para>
	///<para>Value = 127130000</para></summary>
	[Description("+")]
	Empty = 127130000, 
	///<summary><para>-</para>
	///<para>Value = 127130001</para></summary>
	[Description("-")]
	Empty2 = 127130001, 
	///<summary><para>W</para>
	///<para>Value = 127130002</para></summary>
	[Description("W")]
	W = 127130002
}
public enum eStatus
{
	///<summary><para>Active</para>
	///<para>Value = 0</para></summary>
	[Description("Active")]
	Active = 0, 
	///<summary><para>Inactive</para>
	///<para>Value = 1</para></summary>
	[Description("Inactive")]
	Inactive = 1
}
public enum eStatusReason
{
	///<summary><para>Active</para>
	///<para>Value = 1</para></summary>
	[Description("Active")]
	Active_Active = 1, 
	///<summary><para>Manually Deactivated</para>
	///<para>Value = 2</para></summary>
	[Description("Manually Deactivated")]
	ManuallyDeactivated_Inactive = 2, 
	///<summary><para>Validation Errors</para>
	///<para>Value = 127130000</para></summary>
	[Description("Validation Errors")]
	ValidationErrors_Inactive = 127130000, 
	///<summary><para>Deactivated via Bulk Upload</para>
	///<para>Value = 127130001</para></summary>
	[Description("Deactivated via Bulk Upload")]
	DeactivatedViaBulkUpload_Inactive = 127130001
}
public void SetState(IOrganizationService Service, eStatus State, eStatusReason Status)
{
	Service.SetState(this, (int)State, (int)Status);
}
public async System.Threading.Tasks.Task SetStateAsync(IOrganizationService Service, eStatus State, eStatusReason Status)
{
	 await Service.SetStateAsync(this, (int)State, (int)Status);
}


        public static class Properties
{
	/// <summary><para>nhs_parentaccountyominame</para>
	/// <para>nhs_parentaccountyominame</para></summary>
	public const string Nhs_ParentAccountYomiName = "nhs_parentaccountyominame";
	/// <summary><para>modifiedbyyominame</para>
	/// <para>modifiedbyyominame</para></summary>
	public const string ModifiedByYomiName = "modifiedbyyominame";
	/// <summary><para>owneridtype</para>
	/// <para>owneridtype</para></summary>
	public const string OwnerIdType = "owneridtype";
	/// <summary><para>modifiedbyname</para>
	/// <para>modifiedbyname</para></summary>
	public const string ModifiedByName = "modifiedbyname";
	/// <summary><para>owneridname</para>
	/// <para>owneridname</para></summary>
	public const string OwnerIdName = "owneridname";
	/// <summary><para>nhs_parentaccountname</para>
	/// <para>nhs_parentaccountname</para></summary>
	public const string Nhs_ParentAccountName = "nhs_parentaccountname";
	/// <summary><para>createdonbehalfbyyominame</para>
	/// <para>createdonbehalfbyyominame</para></summary>
	public const string CreatedOnBehalfByYomiName = "createdonbehalfbyyominame";
	/// <summary><para>createdonbehalfbyname</para>
	/// <para>createdonbehalfbyname</para></summary>
	public const string CreatedOnBehalfByName = "createdonbehalfbyname";
	/// <summary><para>owneridyominame</para>
	/// <para>owneridyominame</para></summary>
	public const string OwnerIdYomiName = "owneridyominame";
	/// <summary><para>createdbyname</para>
	/// <para>createdbyname</para></summary>
	public const string CreatedByName = "createdbyname";
	/// <summary><para>modifiedonbehalfbyname</para>
	/// <para>modifiedonbehalfbyname</para></summary>
	public const string ModifiedOnBehalfByName = "modifiedonbehalfbyname";
	/// <summary><para>createdbyyominame</para>
	/// <para>createdbyyominame</para></summary>
	public const string CreatedByYomiName = "createdbyyominame";
	/// <summary><para>modifiedonbehalfbyyominame</para>
	/// <para>modifiedonbehalfbyyominame</para></summary>
	public const string ModifiedOnBehalfByYomiName = "modifiedonbehalfbyyominame";
	/// <summary><para>ABO Type</para>
	/// <para>nhs_abotype</para></summary>
	public const string ABOType = "nhs_abotype";
	/// <summary><para>Alternate Key</para>
	/// <para>nhs_alternatekey</para></summary>
	public const string AlternateKey = "nhs_alternatekey";
	/// <summary><para>Antibodies</para>
	/// <para>nhs_antibodies</para></summary>
	public const string Antibodies = "nhs_antibodies";
	/// <summary><para>Associate Antigen on Create - c</para>
	/// <para>nhs_associateantigenoncreate_smallc</para></summary>
	public const string AssociateAntigenOnCreate_C = "nhs_associateantigenoncreate_smallc";
	/// <summary><para>Associate Antigen on Create - C</para>
	/// <para>nhs_associateantigenoncreate_bigc</para></summary>
	public const string AssociateAntigenOnCreate_C2 = "nhs_associateantigenoncreate_bigc";
	/// <summary><para>Associate Antigen on Create - Cw</para>
	/// <para>nhs_associateantigenoncreate_cw</para></summary>
	public const string AssociateAntigenOnCreate_Cw = "nhs_associateantigenoncreate_cw";
	/// <summary><para>Associate Antigen on Create - D</para>
	/// <para>nhs_associateantigenoncreate_d</para></summary>
	public const string AssociateAntigenOnCreate_D = "nhs_associateantigenoncreate_d";
	/// <summary><para>Associate Antigen on Create - e</para>
	/// <para>nhs_associateantigenoncreate_smalle</para></summary>
	public const string AssociateAntigenOnCreate_E = "nhs_associateantigenoncreate_smalle";
	/// <summary><para>Associate Antigen on Create - E</para>
	/// <para>nhs_associateantigenoncreate_bige</para></summary>
	public const string AssociateAntigenOnCreate_E2 = "nhs_associateantigenoncreate_bige";
	/// <summary><para>Associate Antigen on Create - Fya</para>
	/// <para>nhs_associateantigenoncreate_fya</para></summary>
	public const string AssociateAntigenOnCreate_Fya = "nhs_associateantigenoncreate_fya";
	/// <summary><para>Associate Antigen on Create - Fyb</para>
	/// <para>nhs_associateantigenoncreate_fyb</para></summary>
	public const string AssociateAntigenOnCreate_Fyb = "nhs_associateantigenoncreate_fyb";
	/// <summary><para>Associate Antigen on Create - Jka</para>
	/// <para>nhs_associateantigenoncreate_jka</para></summary>
	public const string AssociateAntigenOnCreate_Jka = "nhs_associateantigenoncreate_jka";
	/// <summary><para>Associate Antigen on Create - Jkb</para>
	/// <para>nhs_associateantigenoncreate_jkb</para></summary>
	public const string AssociateAntigenOnCreate_Jkb = "nhs_associateantigenoncreate_jkb";
	/// <summary><para>Associate Antigen on Create - k</para>
	/// <para>nhs_associateantigenoncreate_smallk</para></summary>
	public const string AssociateAntigenOnCreate_K = "nhs_associateantigenoncreate_smallk";
	/// <summary><para>Associate Antigen on Create - K</para>
	/// <para>nhs_associateantigenoncreate_bigk</para></summary>
	public const string AssociateAntigenOnCreate_K2 = "nhs_associateantigenoncreate_bigk";
	/// <summary><para>Associate Antigen on Create - Lea</para>
	/// <para>nhs_associateantigenoncreate_lea</para></summary>
	public const string AssociateAntigenOnCreate_Lea = "nhs_associateantigenoncreate_lea";
	/// <summary><para>Associate Antigen on Create - Leb</para>
	/// <para>nhs_associateantigenoncreate_leb</para></summary>
	public const string AssociateAntigenOnCreate_Leb = "nhs_associateantigenoncreate_leb";
	/// <summary><para>Associate Antigen on Create - M</para>
	/// <para>nhs_associateantigenoncreate_m</para></summary>
	public const string AssociateAntigenOnCreate_M = "nhs_associateantigenoncreate_m";
	/// <summary><para>Associate Antigen on Create - N</para>
	/// <para>nhs_associateantigenoncreate_n</para></summary>
	public const string AssociateAntigenOnCreate_N = "nhs_associateantigenoncreate_n";
	/// <summary><para>Associate Antigen on Create - s</para>
	/// <para>nhs_associateantigenoncreate_smalls</para></summary>
	public const string AssociateAntigenOnCreate_S = "nhs_associateantigenoncreate_smalls";
	/// <summary><para>Associate Antigen on Create - S</para>
	/// <para>nhs_associateantigenoncreate_bigs</para></summary>
	public const string AssociateAntigenOnCreate_S2 = "nhs_associateantigenoncreate_bigs";
	/// <summary><para>Contributor Code</para>
	/// <para>nhs_contributorcode</para></summary>
	public const string ContributorCode = "nhs_contributorcode";
	/// <summary><para>Created By</para>
	/// <para>createdby</para></summary>
	public const string CreatedBy = "createdby";
	/// <summary><para>Created By (Delegate)</para>
	/// <para>createdonbehalfby</para></summary>
	public const string CreatedBy_Delegate = "createdonbehalfby";
	/// <summary><para>Created On</para>
	/// <para>createdon</para></summary>
	public const string CreatedOn = "createdon";
	/// <summary><para>Donor Count</para>
	/// <para>nhs_donorcount</para></summary>
	public const string DonorCount = "nhs_donorcount";
	/// <summary><para>Frozen Unit Count</para>
	/// <para>nhs_frozenunitcount</para></summary>
	public const string FrozenUnitCount = "nhs_frozenunitcount";
	/// <summary><para>Header Row</para>
	/// <para>nhs_headerrow</para></summary>
	public const string HeaderRow = "nhs_headerrow";
	/// <summary><para>Import Sequence Number</para>
	/// <para>importsequencenumber</para></summary>
	public const string ImportSequenceNumber = "importsequencenumber";
	/// <summary><para>Last Reviewed On</para>
	/// <para>nhs_lastreviewedon</para></summary>
	public const string LastReviewedOn = "nhs_lastreviewedon";
	/// <summary><para>Modified By</para>
	/// <para>modifiedby</para></summary>
	public const string ModifiedBy = "modifiedby";
	/// <summary><para>Modified By (Delegate)</para>
	/// <para>modifiedonbehalfby</para></summary>
	public const string ModifiedBy_Delegate = "modifiedonbehalfby";
	/// <summary><para>Modified on</para>
	/// <para>modifiedon</para></summary>
	public const string ModifiedOn = "modifiedon";
	/// <summary><para>Owner</para>
	/// <para>ownerid</para></summary>
	public const string Owner = "ownerid";
	/// <summary><para>Owning Business Unit</para>
	/// <para>owningbusinessunit</para></summary>
	public const string OwningBusinessUnit = "owningbusinessunit";
	/// <summary><para>Owning Team</para>
	/// <para>owningteam</para></summary>
	public const string OwningTeam = "owningteam";
	/// <summary><para>Owning User</para>
	/// <para>owninguser</para></summary>
	public const string OwningUser = "owninguser";
	/// <summary><para>Panel Code</para>
	/// <para>nhs_panelcode</para></summary>
	public const string PanelCode = "nhs_panelcode";
	/// <summary><para>Parent Account</para>
	/// <para>nhs_parentaccount</para></summary>
	public const string ParentAccount = "nhs_parentaccount";
	/// <summary><para>Rare Blood Source</para>
	/// <para>nhs_rarebloodsourceid</para></summary>
	public const string RareBloodSourceId = "nhs_rarebloodsourceid";
	/// <summary><para>rawdata</para>
	/// <para>nhs_rawdata</para></summary>
	public const string Rawdata = "nhs_rawdata";
	/// <summary><para>Record Created On</para>
	/// <para>overriddencreatedon</para></summary>
	public const string RecordCreatedOn = "overriddencreatedon";
	/// <summary><para>Source Type</para>
	/// <para>nhs_sourcetype</para></summary>
	public const string SourceType = "nhs_sourcetype";
	/// <summary><para>Status</para>
	/// <para>statecode</para></summary>
	public const string Status = "statecode";
	/// <summary><para>Status Reason</para>
	/// <para>statuscode</para></summary>
	public const string StatusReason = "statuscode";
	/// <summary><para>Time Zone Rule Version Number</para>
	/// <para>timezoneruleversionnumber</para></summary>
	public const string TimeZoneRuleVersionNumber = "timezoneruleversionnumber";
	/// <summary><para>UTC Conversion Time Zone Code</para>
	/// <para>utcconversiontimezonecode</para></summary>
	public const string UTCConversionTimeZoneCode = "utcconversiontimezonecode";
	/// <summary><para>Version Number</para>
	/// <para>versionnumber</para></summary>
	public const string VersionNumber = "versionnumber";
}

    }
}
